version: '3.7'

services:
  av:
    image: devopstom/docker-clamav:latest
    container_name: av
    restart: unless-stopped
    volumes:
      - clamdata:/var/lib/clamav
    networks:
      - clamnet
    ports:
      - "3110:3110"
  api:
    image: devopstom/go-clamav-rest-echo:latest
    container_name: api
    restart: unless-stopped
    environment:
      - CLAMD_HOST=av
      - CLAMD_PORT=3310
      - LISTEN_PORT=8080
    networks:
      - clamnet
    ports:
      - "8080:8080"

volumes:
  clamdata:

networks:
  clamnet:
